export enum END_POINTS {
    BLANK = '/',
    AWS = '/aws',
    ENC_DEC = '/api/v1/enc-dec',
    MAIN = '/api/v1',
    AUTH = '/auth',
    CHECK_PHONE_EMAIL = '/signup-check-phone-email/:phone/:email',
    ALL = '*',
    USER = '/user',
    ADMIN = '/admin',
    CRAETE_USER = '/create-user',
    LOGIN = '/login',
    INSTRUMENT = '/instrument',
    INSTRUMENT_INSTALL = '/install',
    OPTIONS_STOCK = '/options-stock',
    GET_STRIKE = '/get-strike',
    GET_STRIKE_TO_GENRATE_OPTIONS = '/strik-to-genrate-options',
    HEDGING_INSTALL = '/hedging-time-table-install',
    STOCK = '/stock',
    CREATE_STRATEGY = '/create-strategy',
    TOKEN ='/token',
}
